packages:
  - 'crates/node'
  - 'crates/node/npm/*'
  - 'packages/*'
  - 'playgrounds/*'
  - 'integrations'

catalog:
  '@types/node': ^20.14.8
  lightningcss: ^1.29.1
  prettier: 3.5.0
  vite: ^6.0.0
